# Abstract

# Dataset Description

## Import required modules and download csv file.

In [49]:
import kagglehub
import polars as pl
import os
path = kagglehub.dataset_download("divyansh22/online-gaming-anxiety-data")

print("Path to dataset files:", path)
csv = os.path.join(path, "GamingStudy_data.csv")
df = pl.read_csv(csv, encoding="latin1", null_values="NA")

Path to dataset files: C:\Users\jlgfd\.cache\kagglehub\datasets\divyansh22\online-gaming-anxiety-data\versions\3

# Data Cleaning and Preprocessing


## Drop Unnecessary Columns
These columns were dropped as this study will utlilize the aggregate of these three variables: 
- GAD1 to GAD7 (The Generalized Anxiety Disorder 7)
- SWL1 to SWL5 (Satisfaction with Life Scale)
- SPIN1 to SPIN17 (Social Phobia Inventory)

In [ ]:


dropped_columns = ["S. No.", "GAD1", "GAD2", "GAD3", "GAD4", "GAD5", "GAD6", "GAD7", 
                   "SWL1", "SWL2", "SWL3", "SWL4", "SWL5", "SPIN1","SPIN2","SPIN3",
                   "SPIN4","SPIN5","SPIN6","SPIN7", "SPIN8","SPIN9","SPIN10", "SPIN11", 
                   "SPIN12", "SPIN13", "SPIN14", "SPIN15", "SPIN16", "SPIN17"]

df.drop(dropped_columns)

shape: (13_464, 25)
┌────────────┬────────────┬────────────┬────────────┬───┬───────┬────────┬────────────┬────────────┐
│ Timestamp  ┆ GADE       ┆ Game       ┆ Platform   ┆ … ┆ SWL_T ┆ SPIN_T ┆ Residence_ ┆ Birthplace │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---   ┆ ---    ┆ ISO3       ┆ _ISO3      │
│ f64        ┆ str        ┆ str        ┆ str        ┆   ┆ i64   ┆ i64    ┆ ---        ┆ ---        │
│            ┆            ┆            ┆            ┆   ┆       ┆        ┆ str        ┆ str        │
╞════════════╪════════════╪════════════╪════════════╪═══╪═══════╪════════╪════════════╪════════════╡
│ 42052.0043 ┆ Not        ┆ Skyrim     ┆ Console    ┆ … ┆ 23    ┆ 5      ┆ USA        ┆ USA        │
│ 7          ┆ difficult  ┆            ┆ (PS, Xbox, ┆   ┆       ┆        ┆            ┆            │
│            ┆ at all     ┆            ┆ ...)       ┆   ┆       ┆        ┆            ┆            │
│ 42052.0068 ┆ Somewhat   ┆ Other      ┆ PC         ┆ … ┆ 16    ┆ 33     ┆ USA        ┆ USA        │
│            ┆ difficult  ┆            ┆            ┆   ┆       ┆        ┆            ┆            │
│ 42052.0386 ┆ Not        ┆ Other      ┆ PC         ┆ … ┆ 17    ┆ 31     ┆ DEU        ┆ DEU        │
│            ┆ difficult  ┆            ┆            ┆   ┆       ┆        ┆            ┆            │
│            ┆ at all     ┆            ┆            ┆   ┆       ┆        ┆            ┆            │
│ 42052.0680 ┆ Not        ┆ Other      ┆ PC         ┆ … ┆ 17    ┆ 11     ┆ USA        ┆ USA        │
│ 4          ┆ difficult  ┆            ┆            ┆   ┆       ┆        ┆            ┆            │
│            ┆ at all     ┆            ┆            ┆   ┆       ┆        ┆            ┆            │
│ 42052.0894 ┆ Very       ┆ Other      ┆ Console    ┆ … ┆ 14    ┆ 13     ┆ KOR        ┆ USA        │
│ 8          ┆ difficult  ┆            ┆ (PS, Xbox, ┆   ┆       ┆        ┆            ┆            │
│            ┆            ┆            ┆ ...)       ┆   ┆       ┆        ┆            ┆            │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …     ┆ …      ┆ …          ┆ …          │
│ 42057.7567 ┆ Not        ┆ Other      ┆ Console    ┆ … ┆ 28    ┆ 7      ┆ FRA        ┆ FRA        │
│ 8          ┆ difficult  ┆            ┆ (PS, Xbox, ┆   ┆       ┆        ┆            ┆            │
│            ┆ at all     ┆            ┆ ...)       ┆   ┆       ┆        ┆            ┆            │
│ 42057.8118 ┆ Extremely  ┆ League of  ┆ PC         ┆ … ┆ 23    ┆ 25     ┆ USA        ┆ USA        │
│ 5          ┆ difficult  ┆ Legends    ┆            ┆   ┆       ┆        ┆            ┆            │
│ 42058.1696 ┆ Not        ┆ Starcraft  ┆ PC         ┆ … ┆ 32    ┆ 10     ┆ NOR        ┆ NOR        │
│ 4          ┆ difficult  ┆ 2          ┆            ┆   ┆       ┆        ┆            ┆            │
│            ┆ at all     ┆            ┆            ┆   ┆       ┆        ┆            ┆            │
│ 42058.2442 ┆ Somewhat   ┆ Other      ┆ Console    ┆ … ┆ 16    ┆ 32     ┆ CAN        ┆ CAN        │
│            ┆ difficult  ┆            ┆ (PS, Xbox, ┆   ┆       ┆        ┆            ┆            │
│            ┆            ┆            ┆ ...)       ┆   ┆       ┆        ┆            ┆            │
│ 42058.3637 ┆ Somewhat   ┆ Starcraft  ┆ PC         ┆ … ┆ 25    ┆ 14     ┆ CAN        ┆ CAN        │
│ 5          ┆ difficult  ┆ 2          ┆            ┆   ┆       ┆        ┆            ┆            │
└────────────┴────────────┴────────────┴────────────┴───┴───────┴────────┴────────────┴────────────┘

In [52]:
df["GADE"].unique()

shape: (5,)
Series: 'GADE' [str]
[
	"Very difficult"
	"Extremely difficult"
	"Somewhat difficult"
	"Not difficult at all"
	null
]